'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.32559
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BlixOS_Professional.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajax_loader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajax_loader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blix_logo_pro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blix_logo_pro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blix_logo_pro1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blix_logo_pro1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blix_wallapaper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blix_wallapaper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blogonwpp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blogonwpp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Boot_LoGo___Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Boot_LoGo___Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property browser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("browser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Namespace Webcam
        '''    Public Class Capture
        '''        Const WM_CAP As Short = &amp;H400S
        '''        Const WM_CAP_DRIVER_CONNECT As Integer = WM_CAP + 10
        '''        Const WM_CAP_DRIVER_DISCONNECT As Integer = WM_CAP + 11
        '''        Const WM_CAP_EDIT_COPY As Integer = WM_CAP + 30
        '''        Const WM_CAP_SET_PREVIEW As Integer = WM_CAP + 50
        '''        Const WM_CAP_SET_PREVIEWRATE As Integer = WM_CAP + 52
        '''        Const WM_CAP_SET_SCALE As Integer = WM_CAP + 53
        '''        Const WS_CHILD As Integer = &amp;H40000000
        '''        Const WS_ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CodeFile1() As String
            Get
                Return ResourceManager.GetString("CodeFile1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Delete() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Delete1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Folder_Front() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder_Front", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property FolderDocuments() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FolderDocuments", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt;
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''    Version 2.0
        '''    
        '''    The primary goals of this format is to allow a simple XML format 
        '''    that is mostly human readable. The generation and parsing of the 
        '''    various data types are done through the TypeConverter classes 
        '''    associated with the data types.
        '''    
        '''    Example:
        '''    
        '''    ... ado.net/XML headers &amp; schema ...
        '''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        '''    &lt;resheader n [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Form36() As String
            Get
                Return ResourceManager.GetString("Form36", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()&gt; _
        '''Partial Class Form36
        '''    Inherits ComponentFactory.Krypton.Toolkit.KryptonForm
        '''
        '''    &apos;Form overrides dispose to clean up the component list.
        '''    &lt;System.Diagnostics.DebuggerNonUserCode()&gt; _
        '''    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        '''        If disposing AndAlso components IsNot Nothing Then
        '''            components.Dispose()
        '''        End If
        '''        MyBase.Dispose(disposing)
        '''    End Sub
        '''
        '''    &apos;Required by the W [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Form36_Designer() As String
            Get
                Return ResourceManager.GetString("Form36_Designer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Class Form36
        '''    Const WM_CAP As Short = &amp;H400S
        '''    Const WM_CAP_DRIVER_CONNECT As Integer = WM_CAP + 10
        '''    Const WM_CAP_DRIVER_DISCONNECT As Integer = WM_CAP + 11
        '''    Const WM_CAP_EDIT_COPY As Integer = WM_CAP + 30
        '''    Const WM_CAP_SET_PREVIEW As Integer = WM_CAP + 50
        '''    Const WM_CAP_SET_PREVIEWRATE As Integer = WM_CAP + 52
        '''    Const WM_CAP_SET_SCALE As Integer = WM_CAP + 53
        '''    Const WS_CHILD As Integer = &amp;H40000000
        '''    Const WS_VISIBLE As Integer = &amp;H10000000
        '''    Const SWP_NOMOVE As Sh [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Form361() As String
            Get
                Return ResourceManager.GetString("Form361", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt;
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''    Version 2.0
        '''    
        '''    The primary goals of this format is to allow a simple XML format 
        '''    that is mostly human readable. The generation and parsing of the 
        '''    various data types are done through the TypeConverter classes 
        '''    associated with the data types.
        '''    
        '''    Example:
        '''    
        '''    ... ado.net/XML headers &amp; schema ...
        '''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        '''    &lt;resheader n [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property frmRecognizer() As String
            Get
                Return ResourceManager.GetString("frmRecognizer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()&gt; _
        '''Partial Class frmRecognizer
        '''    Inherits ComponentFactory.Krypton.Toolkit.KryptonForm
        '''
        '''    &apos;Form overrides dispose to clean up the component list.
        '''    &lt;System.Diagnostics.DebuggerNonUserCode()&gt; _
        '''    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        '''        If disposing AndAlso components IsNot Nothing Then
        '''            components.Dispose()
        '''        End If
        '''        MyBase.Dispose(disposing)
        '''    End Sub
        '''
        '''    &apos;Required b [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property frmRecognizer_Designer() As String
            Get
                Return ResourceManager.GetString("frmRecognizer_Designer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Option Strict On
        '''
        '''Imports Microsoft.Ink
        '''
        '''Public Class frmRecognizer
        '''
        '''    &apos;Ink collecting object
        '''    Private inkOverlay As InkOverlay
        '''
        '''    &apos;Active recognizer
        '''    Friend activeRecognizer As Recognizer
        '''
        '''    Sub New()
        '''        InitializeComponent()
        '''
        '''        &apos;Gather ink on the panel
        '''        inkOverlay = New InkOverlay(Panel1)
        '''        &apos;Activate ink-gathering
        '''        inkOverlay.Enabled = True
        '''
        '''        &apos;Get all the installed recognizers
        '''        Dim recognizers As New Recognizers()
        '''
        '''        &apos;Ge [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property frmRecognizer1() As String
            Get
                Return ResourceManager.GetString("frmRecognizer1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Genuine_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Genuine_Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Get_Info() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Get_Info", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Get_Info1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Get_Info1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Library() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Library", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loadinfo_net() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadinfo_net", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loadinfo_net_R_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadinfo_net_R_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loadinfo_net1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadinfo_net1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_big1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_big1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property logo_ico() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_ico", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Music() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Music", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Muzik_1_X2_4() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Muzik_1_X2_4", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property my_docs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("my_docs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property my_pictures() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("my_pictures", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property MyComputer() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("MyComputer", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property personalize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("personalize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Pictures() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Pictures", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rename() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rename", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property sound() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("sound", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text2bin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text2bin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Trash_empty() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Trash_empty", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property webcam_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("webcam_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
